### ISSUE TITLE
Certain Courses Counting as 9 Credits

### ISSUE THREAD

**Issue by scchow** [bitsofpancake/hmc-scheduler#6]
Some classes are being counted as 3 times the number of credits they should be.
These include:
- ENGR190ABHM-01
- ENGR190ACHM-01
- ENG190ADHM-01

and any others that do not have a space before HM in the course code.

I believe the issue is at line 499-504 in scheduler.js

```
      // Mudd courses are worth their full value.
      if (course.data['courseCode'].indexOf(' HM-') != -1)
        return course.data['credits'];

      // Other colleges' courses need to be multiplied by three.
      return course.data['credits'] * 3;
```

Perhaps we want a better way of detecting Mudd courses. Or for now, just delete the space in `' HM-'` . :)

**Comment by alex-ozdemir** [comment]
Nice spot!

I can fix this, but if you'd like to get the credit how about you submit a PR?
