### ISSUE TITLE
Option links

### ISSUE THREAD

**Issue by dolumese** [bitsofpancake/hmc-scheduler#8]
When the browser tab is refreshed, the check boxes are marked checked irrespective of their actual saved values in localStorage. 
The option values are correctly saved, however it isn't reflected on the checked state of the check boxes after researching.

**Comment by alex-ozdemir** [comment]
Thanks for filing an issue. I'm not sure that I understand the bug you're reporting though -- can you help me reproduce it?

I did the following:
1. I open the scheduler in a new tab.
2. I checked and unchecked boxes until classes A and B were checked, and C was not.
3. I hit "generate"
4. I unchecked class A.
5. I refreshed the page. This resulted in a schedule only containing class B being displayed, and only class B was checked.

So far, this seems like desirable behavior, but perhaps I am missing something, or I should take different steps.

**Comment by dolumese** [comment]
That wasn't the best of descriptions. I'll try again.
It's not the classes check boxes but the scheduler options check boxes (`allowConflicts` & `showSections`)

Steps to reproduce:
* Open the scheduler
* Add a new course
    ![1](https://cloud.githubusercontent.com/assets/21287840/21579855/9483e13c-cf7b-11e6-88a9-40458bc744af.PNG)
    If you inspect element, then navigation to application and expand the localStorage tab, you should see something similar to the following (nit: by default the options values are set to false but it doesn't in the DOM)
    ![1-1](https://cloud.githubusercontent.com/assets/21287840/21579854/947e704e-cf7b-11e6-926f-377988aceacf.PNG)
* Check both Allow Conflicts and Show Sections
    ![2](https://cloud.githubusercontent.com/assets/21287840/21579853/946cd50a-cf7b-11e6-9ac5-cdd512f8b94e.PNG)
    ![2-1](https://cloud.githubusercontent.com/assets/21287840/21579852/946a03ac-cf7b-11e6-8f53-9bf2d4e63c8f.PNG)
* Now uncheck one of the options (in this case, Show Sections)
    ![3](https://cloud.githubusercontent.com/assets/21287840/21579851/9469ca0e-cf7b-11e6-890d-1a47a918d440.PNG)
    ![3-1](https://cloud.githubusercontent.com/assets/21287840/21579850/94687e42-cf7b-11e6-95f6-d2d67210c6fe.PNG)
* Now if you refresh the tab, the Show Sections is marked as checked although it's option value is still false as it should be
    ![4](https://cloud.githubusercontent.com/assets/21287840/21579848/94668dd0-cf7b-11e6-8525-8785ec5fedf7.PNG)
    ![4-1](https://cloud.githubusercontent.com/assets/21287840/21579849/9466edf2-cf7b-11e6-8f7b-0470704c8edd.PNG)

The locally stored values of the options are reflected in the scheduler UI.

I believe I found the bug:
`localStorage.showSections` stores the boolean values as strings so `document.getElementById('button-sections').checked = options.showSections = localStorage.showSections` fails to set the value of checked correctly as it expects a boolean not a string.
Changing those lines to `document.getElementById('button-sections').checked = options.showSections = (localStorage.showSections === 'true')` should solve the issue.

Please debug and confirm.
Thank you 😄
